try {
function _throw(e) {
    throw e;
}
export { _throw as _ };

} catch (error) { console.error(error); }