try {
export default function number(x) {
  return +x;
}

} catch (error) { console.error(error); }